services:
  clickhouse:
#    24.8 = LTS version
    image: clickhouse/clickhouse-server:24.8.11.5
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - 'clickhouse_data:/var/lib/clickhouse'
      - './plugins/clickhouse-knowledge-graph/config:/etc/clickhouse-server/users.d'
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  kvasir-ui:
    build: https://bot:sufPJVx5suVPs3W9kqxy@gitlab.ilabt.imec.be/ibcndevs/solid/kvasir-ui.git#main
    ports:
      - "3000:4200"
    pull_policy: build

volumes:
  clickhouse_data:
    driver: local