package kvasir.definitions.kg.graphql

const val TYPE_MUTATION = "Mutation"

const val FIELD_ID_NAME = "id"
const val DIRECTIVE_CLASS_NAME = "class"
const val DIRECTIVE_PREDICATE_NAME = "predicate"
const val DIRECTIVE_SHAPE_NAME = "shape"
const val DIRECTIVE_OPTIONAL_NAME = "optional"
const val DIRECTIVE_FILTER_NAME = "filter"
const val DIRECTIVE_GRAPH_NAME = "graph"
const val DIRECTIVE_STORAGE_NAME = "storage"
const val ARG_IRI_NAME = "iri"
const val ARG_REVERSE_NAME = "reverse"
const val ARG_IF_NAME = "if"
const val ARG_CLASS_NAME = "class"
const val ARG_MIN_COUNT_NAME = "minCount"
const val ARG_MAX_COUNT_NAME = "maxCount"
const val ARG_MIN_INCLUSIVE_NAME = "minInclusive"
const val ARG_MAX_INCLUSIVE_NAME = "maxInclusive"
const val ARG_MIN_EXCLUSIVE_NAME = "minExclusive"
const val ARG_MAX_EXCLUSIVE_NAME = "maxExclusive"
const val ARG_MIN_LENGTH_NAME = "minLength"
const val ARG_MAX_LENGTH_NAME = "maxLength"
const val ARG_PATTERN_NAME = "pattern"
const val ARG_FLAGS_NAME = "flags"
const val ARG_HAS_VALUE_NAME = "hasValue"
const val ARG_IN_NAME = "in"
const val ARG_PAGE_SIZE_NAME = "pageSize"
const val ARG_CURSOR_NAME = "cursor"
const val ARG_ORDER_BY_NAME = "orderBy"
const val ARG_ID_NAME = "id"