kvasir:
  bootstrap:
    pods:
      - name: alice
        default-context:
          kss: https://kvasir.discover.ilabt.imec.be/vocab#
          rdfs: http://www.w3.org/2000/01/rdf-schema#
          xsd: http://www.w3.org/2001/XMLSchema#
          schema: http://schema.org/
          ex: http://example.org/
        auto-ingest-rdf: true