kvasir:
  services:
    storage:
      s3:
        host: localhost
        port: ${quarkus.minio.port}
        access-key: ${quarkus.minio.access-key}
        secret-key: ${quarkus.minio.secret-key}
quarkus:
  http:
    cors:
      ~: true
      origins: /.*/
      exposed-headers: Link, Location
  minio:
    devservices:
  smallrye-openapi:
    store-schema-directory: target/openapi

"%dev":
  quarkus:
    http:
      cors:
        ~: true
        origins: http://localhost:3000,http://localhost:4200
  kvasir:
    bootstrap:
      pods:
        - name: alicebob
          default-context: |
            {
              "kss": "https://kvasir.discover.ilabt.imec.be/vocab#",
              "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
              "xsd": "http://www.w3.org/2001/XMLSchema#",
              "schema": "http://schema.org/",
              "ex": "http://example.org/"
            }
          auto-ingest-rdf: false
        - name: alice
          default-context: |
            {
              "kss": "https://kvasir.discover.ilabt.imec.be/vocab#",
              "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
              "xsd": "http://www.w3.org/2001/XMLSchema#",
              "schema": "http://schema.org/",
              "ex": "http://example.org/",
              "saref": "https://saref.etsi.org/core/",
              "hasMeasurement": {
                "@reverse": "https://saref.etsi.org/core/measurementMadeBy"
              },
              "children": { "@reverse": "http://example.org/parent" }
            }
          auto-ingest-rdf: true
        - name: alicebob
          default-context: |
            {
              "kss": "https://kvasir.discover.ilabt.imec.be/vocab#",
              "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
              "xsd": "http://www.w3.org/2001/XMLSchema#",
              "schema": "http://schema.org/",
              "ex": "http://example.org/"
            }
            auto-ingest-rdf: false
        - name: bob
          default-context: |
            {
              "kss": "https://kvasir.discover.ilabt.imec.be/vocab#",
              "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
              "xsd": "http://www.w3.org/2001/XMLSchema#",
              "schema": "http://schema.org/",
              "ex": "http://example.org/"
            }
          auto-ingest-rdf: false
        - name: bob1
          default-context: |
            {
              "kss": "https://kvasir.discover.ilabt.imec.be/vocab#",
              "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
              "xsd": "http://www.w3.org/2001/XMLSchema#",
              "schema": "http://schema.org/",
              "ex": "http://example.org/"
            }
          auto-ingest-rdf: false
        - name: bob2
          default-context: |
            {
              "kss": "https://kvasir.discover.ilabt.imec.be/vocab#",
              "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
              "xsd": "http://www.w3.org/2001/XMLSchema#",
              "schema": "http://schema.org/",
              "ex": "http://example.org/"
            }
          auto-ingest-rdf: false
        - name: bob3
          default-context: |
            {
              "kss": "https://kvasir.discover.ilabt.imec.be/vocab#",
              "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
              "xsd": "http://www.w3.org/2001/XMLSchema#",
              "schema": "http://schema.org/",
              "ex": "http://example.org/"
            }
          auto-ingest-rdf: false
        - name: bob4
          default-context: |
            {
              "kss": "https://kvasir.discover.ilabt.imec.be/vocab#",
              "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
              "xsd": "http://www.w3.org/2001/XMLSchema#",
              "schema": "http://schema.org/",
              "ex": "http://example.org/"
            }
          auto-ingest-rdf: false
        - name: bob5
          default-context: |
            {
              "kss": "https://kvasir.discover.ilabt.imec.be/vocab#",
              "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
              "xsd": "http://www.w3.org/2001/XMLSchema#",
              "schema": "http://schema.org/",
              "ex": "http://example.org/"
            }
          auto-ingest-rdf: false
        - name: bob6
          default-context: |
            {
              "kss": "https://kvasir.discover.ilabt.imec.be/vocab#",
              "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
              "xsd": "http://www.w3.org/2001/XMLSchema#",
              "schema": "http://schema.org/",
              "ex": "http://example.org/"
            }
          auto-ingest-rdf: false
        - name: bob7
          default-context: |
            {
              "kss": "https://kvasir.discover.ilabt.imec.be/vocab#",
              "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
              "xsd": "http://www.w3.org/2001/XMLSchema#",
              "schema": "http://schema.org/",
              "ex": "http://example.org/"
            }
          auto-ingest-rdf: false
        - name: bob8
          default-context: |
            {
              "kss": "https://kvasir.discover.ilabt.imec.be/vocab#",
              "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
              "xsd": "http://www.w3.org/2001/XMLSchema#",
              "schema": "http://schema.org/",
              "ex": "http://example.org/"
            }
          auto-ingest-rdf: false
        - name: bob9
          default-context: |
            {
              "kss": "https://kvasir.discover.ilabt.imec.be/vocab#",
              "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
              "xsd": "http://www.w3.org/2001/XMLSchema#",
              "schema": "http://schema.org/",
              "ex": "http://example.org/"
            }
          auto-ingest-rdf: false
        - name: bob10
          default-context: |
            {
              "kss": "https://kvasir.discover.ilabt.imec.be/vocab#",
              "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
              "xsd": "http://www.w3.org/2001/XMLSchema#",
              "schema": "http://schema.org/",
              "ex": "http://example.org/"
            }
          auto-ingest-rdf: false
        - name: swdemo
          default-context: |
            {
              "@language": "en",
              "kss": "https://kvasir.discover.ilabt.imec.be/vocab#",
              "voc": "https://swapi.co/vocabulary/",
              "commons": "https://commons.wikimedia.org/wiki/Special:FilePath/",
              "dc": "http://purl.org/dc/elements/1.1/",
              "dct": "http://purl.org/dc/terms/",
              "owl": "http://www.w3.org/2002/07/owl#",
              "p": "http://www.wikidata.org/prop/",
              "pq": "http://www.wikidata.org/prop/qualifier/",
              "ps": "http://www.wikidata.org/prop/statement/",
              "rdf": "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
              "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
              "wd": "http://www.wikidata.org/entity/",
              "wds": "http://www.wikidata.org/entity/statement/",
              "wdt": "http://www.wikidata.org/prop/direct/",
              "wgs": "http://www.w3.org/2003/01/geo/wgs84_pos#",
              "wikibase": "http://wikiba.se/ontology#",
              "xml": "http://www.w3.org/XML/1998/namespace",
              "xsd": "http://www.w3.org/2001/XMLSchema#"
            }
          auto-ingest-rdf: true